### ISSUE TITLE
请问astilectron怎么导入啊？

### ISSUE THREAD

**Issue by 39499740** [im050/awesome-hosts#1]
我是个新手，想用go-astilectron，但是不知道vue这边怎么导入astilectron，现在我发消息说astilectron未定义，请问你们是怎么导入的？

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by im050** [comment]
> 我是个新手，想用go-astilectron，但是不知道vue这边怎么导入astilectron，现在我发消息说astilectron未定义，请问你们是怎么导入的？
> 
> :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

配置ResourcesPath
```
ResourcesPath: "src/dist",
```
或者将
```
npm run build
```
编译后的代码放置到resources/app/目录下

如果你用的是`vue-cli 3.x`创建的vue项目，可以参考这个项目的`vue.config.js`及目录结构

[https://github.com/ensonmj/go-astilectron-vue-demo/blob/master/ui/vue.config.js](https://github.com/ensonmj/go-astilectron-vue-demo/blob/master/ui/vue.config.js)

或者参考配置ResourcesPath的方式

[https://github.com/ZEROKISEKI/starsManager/blob/master/main.go](https://github.com/ZEROKISEKI/starsManager/blob/master/main.go)

**Comment by 39499740** [comment]
我看到你的项目中,发消息的方法跟官网写的不一样,请问你这边是有其他文档么?

**Comment by im050** [comment]
> 我看到你的项目中,发消息的方法跟官网写的不一样,请问你这边是有其他文档么?

一样的，只是重新封装过。

**Comment by 39499740** [comment]
好的，谢谢，我在研究一下
